"""add preferences model

Revision ID: 5a1711d5bbe4
Revises: 
Create Date: 2025-05-01 16:22:32.265311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1711d5bbe4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('meal_name', sa.String(), nullable=False))
    op.add_column('preferences', sa.Column('rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'rating')
    op.drop_column('preferences', 'meal_name')
    # ### end Alembic commands ###
